CREATE TABLE upload_batches (
    id CHAR(36) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_url TEXT NOT NULL,
    file_checksum CHAR(64) NOT NULL,
    uploaded_by CHAR(36) NOT NULL,
    status ENUM('pending', 'processing', 'validated', 'failed', 'imported', 'partially_imported', 'cancelled') NOT NULL DEFAULT 'pending',
    total_rows INT NOT NULL DEFAULT 0,
    valid_rows INT NOT NULL DEFAULT 0,
    invalid_rows INT NOT NULL DEFAULT 0,
    duplicate_rows INT NOT NULL DEFAULT 0,
    skipped_rows INT NOT NULL DEFAULT 0,
    preview_expires_at DATETIME(3) NULL,
    error_file_url TEXT NULL,
    processing_started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    created_by CHAR(36) NULL,
    updated_by CHAR(36) NULL,
    PRIMARY KEY (id),
    KEY idx_upload_batches_uploaded_by_created_at (uploaded_by, created_at),
    KEY idx_upload_batches_status_created_at (status, created_at),
    CONSTRAINT fk_upload_batches_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id),
    CONSTRAINT fk_upload_batches_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_upload_batches_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE upload_batch_rows (
    id CHAR(36) NOT NULL,
    upload_batch_id CHAR(36) NOT NULL,
    csv_row_number INT NOT NULL,
    customer_id VARCHAR(100) NULL,
    customer_name VARCHAR(255) NULL,
    customer_type ENUM('new', 'returning') NULL,
    mobilisation_date DATE NULL,
    investment_amount DECIMAL(19,4) NULL,
    fund_type ENUM('inflow', 'rollover') NULL,
    tenor_days INT NULL,
    tenor_category ENUM('short_term', 'mid_short_term', 'medium_term', 'long_term', 'unclassified') NULL,
    maturity_date DATE NULL,
    investment_reference VARCHAR(150) NULL,
    currency CHAR(3) NOT NULL DEFAULT 'NGN',
    source_channel VARCHAR(100) NULL,
    relationship_manager VARCHAR(150) NULL,
    cost_of_funds DECIMAL(9,6) NULL,
    source_record_hash CHAR(64) NULL,
    row_status ENUM('valid', 'invalid', 'duplicate', 'skipped') NOT NULL,
    raw_payload_json JSON NULL,
    normalized_payload_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_upload_batch_rows_batch_row_number (upload_batch_id, csv_row_number),
    KEY idx_upload_batch_rows_status (row_status),
    KEY idx_upload_batch_rows_reference (investment_reference),
    CONSTRAINT fk_upload_batch_rows_upload_batch_id FOREIGN KEY (upload_batch_id) REFERENCES upload_batches (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE upload_validation_errors (
    id CHAR(36) NOT NULL,
    upload_batch_id CHAR(36) NOT NULL,
    upload_batch_row_id CHAR(36) NULL,
    csv_row_number INT NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    error_code VARCHAR(100) NOT NULL,
    error_message TEXT NOT NULL,
    original_value TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_upload_validation_errors_batch_row (upload_batch_id, csv_row_number),
    KEY idx_upload_validation_errors_field_name (field_name),
    CONSTRAINT fk_upload_validation_errors_upload_batch_id FOREIGN KEY (upload_batch_id) REFERENCES upload_batches (id),
    CONSTRAINT fk_upload_validation_errors_upload_batch_row_id FOREIGN KEY (upload_batch_row_id) REFERENCES upload_batch_rows (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;