CREATE TABLE investment_records (
    id CHAR(36) NOT NULL,
    customer_id VARCHAR(100) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_type ENUM('new', 'returning') NOT NULL,
    mobilisation_date DATE NOT NULL,
    investment_amount DECIMAL(19,4) NOT NULL,
    fund_type ENUM('inflow', 'rollover') NOT NULL,
    tenor_days INT NOT NULL,
    tenor_category ENUM('short_term', 'mid_short_term', 'medium_term', 'long_term', 'unclassified') NOT NULL,
    maturity_date DATE NULL,
    investment_reference VARCHAR(150) NULL,
    currency CHAR(3) NOT NULL DEFAULT 'NGN',
    source_channel VARCHAR(100) NULL,
    relationship_manager VARCHAR(150) NULL,
    cost_of_funds DECIMAL(9,6) NULL,
    import_batch_id CHAR(36) NULL,
    upload_batch_row_id CHAR(36) NULL,
    sync_batch_id CHAR(36) NULL,
    data_source ENUM('csv_upload', 'api_sync', 'db_sync') NOT NULL,
    import_status ENUM('pending', 'confirmed', 'rejected', 'archived') NOT NULL DEFAULT 'pending',
    record_status ENUM('valid', 'invalid', 'duplicate', 'archived') NOT NULL DEFAULT 'valid',
    source_record_hash CHAR(64) NULL,
    confirmed_by CHAR(36) NULL,
    confirmed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    created_by CHAR(36) NULL,
    updated_by CHAR(36) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_investment_records_reference (investment_reference),
    UNIQUE KEY uk_investment_records_source_hash (source_record_hash),
    KEY idx_investment_records_dashboard_filter (record_status, import_status, mobilisation_date),
    KEY idx_investment_records_customer_id (customer_id),
    KEY idx_investment_records_customer_type (customer_type),
    KEY idx_investment_records_fund_type (fund_type),
    KEY idx_investment_records_tenor_category (tenor_category),
    KEY idx_investment_records_relationship_manager (relationship_manager),
    KEY idx_investment_records_source_channel (source_channel),
    KEY idx_investment_records_import_batch_id (import_batch_id),
    KEY idx_investment_records_sync_batch_id (sync_batch_id),
    CONSTRAINT chk_investment_records_amount_positive CHECK (investment_amount > 0),
    CONSTRAINT chk_investment_records_tenor_positive CHECK (tenor_days > 0),
    CONSTRAINT fk_investment_records_import_batch_id FOREIGN KEY (import_batch_id) REFERENCES upload_batches (id),
    CONSTRAINT fk_investment_records_upload_batch_row_id FOREIGN KEY (upload_batch_row_id) REFERENCES upload_batch_rows (id),
    CONSTRAINT fk_investment_records_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES users (id),
    CONSTRAINT fk_investment_records_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_investment_records_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE idempotency_keys (
    id CHAR(36) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    scope ENUM('upload_confirm', 'sync_trigger', 'report_export') NOT NULL,
    actor_id CHAR(36) NOT NULL,
    resource_type VARCHAR(100) NOT NULL,
    resource_id CHAR(36) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    response_status SMALLINT NOT NULL,
    response_body_json JSON NULL,
    locked_until DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    expires_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_idempotency_scope_key (scope, idempotency_key),
    KEY idx_idempotency_actor_scope_created_at (actor_id, scope, created_at),
    CONSTRAINT fk_idempotency_keys_actor_id FOREIGN KEY (actor_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;