CREATE TABLE audit_logs (
    id CHAR(36) NOT NULL,
    actor_id CHAR(36) NULL,
    actor_role VARCHAR(50) NOT NULL,
    actor_type ENUM('admin', 'analyst', 'uploader', 'system') NOT NULL,
    action VARCHAR(150) NOT NULL,
    resource_type VARCHAR(100) NOT NULL,
    resource_id VARCHAR(100) NOT NULL,
    outcome ENUM('success', 'failed', 'partial_success') NOT NULL,
    before_json JSON NULL,
    after_json JSON NULL,
    metadata_json JSON NULL,
    ip_address VARCHAR(100) NULL,
    user_agent TEXT NULL,
    request_id VARCHAR(100) NULL,
    correlation_id VARCHAR(100) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_audit_logs_actor_id_created_at (actor_id, created_at),
    KEY idx_audit_logs_action_created_at (action, created_at),
    KEY idx_audit_logs_resource (resource_type, resource_id),
    KEY idx_audit_logs_correlation_id (correlation_id),
    CONSTRAINT fk_audit_logs_actor_id FOREIGN KEY (actor_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;