CREATE TABLE outbox_events (
    id CHAR(36) NOT NULL,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id CHAR(36) NOT NULL,
    event_type VARCHAR(150) NOT NULL,
    event_version INT NOT NULL DEFAULT 1,
    payload_json JSON NOT NULL,
    headers_json JSON NULL,
    correlation_id VARCHAR(100) NOT NULL,
    request_id VARCHAR(100) NULL,
    occurred_at DATETIME(3) NOT NULL,
    status ENUM('pending', 'dispatched', 'failed') NOT NULL DEFAULT 'pending',
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at DATETIME(3) NULL,
    dispatched_at DATETIME(3) NULL,
    last_error_message TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_outbox_events_status_next_attempt_at (status, next_attempt_at),
    KEY idx_outbox_events_aggregate (aggregate_type, aggregate_id),
    KEY idx_outbox_events_event_type (event_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE job_history (
    id CHAR(36) NOT NULL,
    queue_name VARCHAR(100) NOT NULL,
    job_name VARCHAR(150) NOT NULL,
    job_id VARCHAR(150) NOT NULL,
    request_id VARCHAR(100) NULL,
    correlation_id VARCHAR(100) NOT NULL,
    actor_snapshot_json JSON NULL,
    source_type ENUM('csv_upload', 'api_sync', 'db_sync', 'report_export', 'notification', 'outbox') NOT NULL,
    batch_id CHAR(36) NULL,
    status ENUM('queued', 'running', 'completed', 'failed', 'dead_lettered', 'cancelled') NOT NULL,
    attempts_made INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 1,
    error_message TEXT NULL,
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_job_history_job (queue_name, job_id),
    KEY idx_job_history_status_created_at (status, created_at),
    KEY idx_job_history_batch_id (batch_id),
    KEY idx_job_history_correlation_id (correlation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;